#include "ChannelCatalog.h"

const ChannelDefinition CHANNELS[CHANNEL_COUNT] = {
    {"Ch01", "/ch/", 1, true},       {"Ch02", "/ch/", 2, true},
    {"Ch03", "/ch/", 3, true},       {"Ch04", "/ch/", 4, true},
    {"Ch05", "/ch/", 5, true},       {"Ch06", "/ch/", 6, true},
    {"Ch07", "/ch/", 7, true},       {"Ch08", "/ch/", 8, true},
    {"Ch09", "/ch/", 9, true},       {"Ch10", "/ch/", 10, true},
    {"Ch11", "/ch/", 11, true},      {"Ch12", "/ch/", 12, true},
    {"Ch13", "/ch/", 13, true},      {"Ch14", "/ch/", 14, true},
    {"Ch15", "/ch/", 15, true},      {"Ch16", "/ch/", 16, true},
    {"Ch17", "/ch/", 17, true},      {"Ch18", "/ch/", 18, true},
    {"Ch19", "/ch/", 19, true},      {"Ch20", "/ch/", 20, true},
    {"Ch21", "/ch/", 21, true},      {"Ch22", "/ch/", 22, true},
    {"Ch23", "/ch/", 23, true},      {"Ch24", "/ch/", 24, true},
    {"Ch25", "/ch/", 25, true},      {"Ch26", "/ch/", 26, true},
    {"Ch27", "/ch/", 27, true},      {"Ch28", "/ch/", 28, true},
    {"Ch29", "/ch/", 29, true},      {"Ch30", "/ch/", 30, true},
    {"Ch31", "/ch/", 31, true},      {"Ch32", "/ch/", 32, true},
    {"Aux01", "/auxin/", 1, true},   {"Aux02", "/auxin/", 2, true},
    {"Aux03", "/auxin/", 3, true},   {"Aux04", "/auxin/", 4, true},
    {"Aux05", "/auxin/", 5, true},   {"Aux06", "/auxin/", 6, true},
    {"Aux07", "/auxin/", 7, true},   {"Aux08", "/auxin/", 8, true},
    {"FX01", "/fxrtn/", 1, true},    {"FX02", "/fxrtn/", 2, true},
    {"FX03", "/fxrtn/", 3, true},    {"FX04", "/fxrtn/", 4, true},
    {"FX05", "/fxrtn/", 5, true},    {"FX06", "/fxrtn/", 6, true},
    {"FX07", "/fxrtn/", 7, true},    {"FX08", "/fxrtn/", 8, true},
    {"Bus01", "/bus/", 1, true},     {"Bus02", "/bus/", 2, true},
    {"Bus03", "/bus/", 3, true},     {"Bus04", "/bus/", 4, true},
    {"Bus05", "/bus/", 5, true},     {"Bus06", "/bus/", 6, true},
    {"Bus07", "/bus/", 7, true},     {"Bus08", "/bus/", 8, true},
    {"Bus09", "/bus/", 9, true},     {"Bus10", "/bus/", 10, true},
    {"Bus11", "/bus/", 11, true},    {"Bus12", "/bus/", 12, true},
    {"Bus13", "/bus/", 13, true},    {"Bus14", "/bus/", 14, true},
    {"Bus15", "/bus/", 15, true},    {"Bus16", "/bus/", 16, true},
    {"Mtx01", "/mtx/", 1, true},     {"Mtx02", "/mtx/", 2, true},
    {"Mtx03", "/mtx/", 3, true},     {"Mtx04", "/mtx/", 4, true},
    {"Mtx05", "/mtx/", 5, true},     {"Mtx06", "/mtx/", 6, true},
    {"Main", "/main/st", 0, false},   {"Mono", "/main/m", 0, false},
};
